name: Release fosslight_scanner

on:
  release:
    types: [published]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: versionUpTest
    - name: Get Release
      uses: bruceadams/get-release@v1.3.2
      id: get_release
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Bump up version
      env:
        NEW_TAG: ${{ steps.get_release.outputs.tag_name }}
      run: |
        pip install --upgrade bumpversion
        LAST_TWO_TAGS=$(git for-each-ref refs/tags/ --count=2 --sort=-v:refname --format="%(refname:short)")
        LAST_ONE=$(echo $LAST_TWO_TAGS | cut -d' ' -f 2)
        last_version=$(echo ${LAST_ONE//v/""})
        echo Last version: ${last_version}
        new_version=$(echo ${NEW_TAG//v/""})
        echo New version: ${new_version}
        git config --global user.name "github-actions[bot]"
        git config --global user.email "fosslight-dev@lge.com"
        bumpversion --current-version $last_version --new-version $new_version setup.py
    - name: update changelog with gren
      env:
        GREN_GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        npm install github-release-notes@0.17.3
        node_modules/.bin/gren changelog --override
    - name: Commit files
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "fosslight-dev@lge.com"
        git add .
        git commit -m "Update ChangeLog"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        branch: versionUpTest

  deploy-test:
    runs-on: ubuntu-latest
    needs: update-changelog
    steps:
    - uses: actions/checkout@v3
      with:
        ref: versionUpTest
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish to Test PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload --repository testpypi dist/*

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-test
    if: github.event.release.prerelease == false
    steps:
    - uses: actions/checkout@v3
      with:
        ref: versionUpTest
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*